title: Open Source Software and AI Tools Collection for PQFIF (Post-Quantum Financial Infrastructure Framework)
email: caishu@flomesh.io
description: >- 
  OpenSource Software and AI tools for PQFIF. 
baseurl: "" 
url: "https://pqfif-oss.ai" 

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme

github_username: caishu97
linkedin_username: caishu97

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
