title: Open Source Software Collection for PQFIF (Post-Quantum Financial Infrastructure Framework)
email: caishu@flomesh.io
description: >- 
  pqfif-oss is a collection of open-source projects and AI resources that we have organized, gathered, and created to meet and implement the PQFIF. It aims to provide tools, methodologies, and reference practices for professionals working in the PQFIF field. 
baseurl: "" 
url: "https://pqfif-oss.ai" 

theme: jekyll-theme-minimal 

github_username: caishu97
linkedin_username: caishu97

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
